#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults

echo '
-------------------------------------
              _      __     
             | |    / _|    
   __ _  ___ | |__ | |_ ___ 
  / _  |/ _ \|  _ \|  _/ __|
 | (_| | (_) | | | | | \__ \
  \__  |\___/|_| |_|_| |___/
   __/ |                    
  |___/                     

Docker Image of github.com/finzzz/gohfs'
echo "
-------------------------------------
GID/UID
-------------------------------------
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"
