version: '3.7'

services:
  gohfs:
    build: '.'
    image: finzzz/gohfs:latest
    container_name: gohfs
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - webserver
    volumes:
      - ./data:/data              # Data folder for gohfs to serve
    environment:
      - TZ=Europe/Zurich          # Time Zone for the container (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
      - PUID=1000                 # Unix user ID to run the container as (default 911)
      - PGID=1000                 # Unix group ID to run the container as (default 911)
#      - GOHFS_HOST=              # IP address on which the webserver listens (default: 0.0.0.0) 
#      - GOHFS_PORT=              # Port on which the webserver listens (default: 8080) 
#      - GOHFS_USER=              # Username for authentification (default: disabled)
#      - GOHFS_PASSWORD=          # Sha256 hashed password for authentification (default: disabled)
#      - GOHFS_PASSWORD_RAW=      # Raw (cleartext) password for authentification (default: disabled)
#      - GOHFS_MAXUP=             # Maximum upload size in Bytes (default -1)
#      - GOHFS_ARGS=              # Additional gohfs command-line arguments, separated with spaces (e.g. "-dz -du -dl")
      
networks:
  webserver:
    driver: bridge
